export const W = 1280;
export const H = 720;
export type Weapon = 'TWIN' | 'SPREAD' | 'LASER' | 'HOMING';
export type ShipId = 'A' | 'B' | 'C' | 'D' | 'E';
export type AllyId = 'mira' | 'gale' | 'noa';
export type Mode = 'story' | 'attack';
export type Action = 'shoot' | 'bomb' | 'dash' | 'slow' | 'hyper' | 'pause' | 'weapon';
export type EnemyKind = 'scout' | 'fast' | 'rammer' | 'missile' | 'sniper' | 'laser' | 'shield' | 'drone' | 'mother' | 'cruiser' | 'turret' | 'midboss' | 'boss';
export type Point = { x: number; y: number };
export type Rect = Point & { w: number; h: number };
export type Input = { moveX: number; moveY: number; target: Point | null } & Record<Action, boolean>;
export type Settings = { autoShot: boolean; touchOffset: number; music: number; sfx: number; reducedMotion: boolean; difficulty: 'EASY' | 'NORMAL' | 'HARD' };
export type Save = { version: 2; cleared: number[]; unlocked: ShipId[]; selected: ShipId; allies: AllyId[]; choices: Record<string, string>; nextStage: number; highs: Record<Mode, number>; settings: Settings };
export type Bullet = Rect & { vx: number; vy: number; power: number; friendly: boolean; weapon: Weapon; life: number; grazed: boolean; hits: number[]; pierce: boolean };
export type Enemy = Rect & { id: number; kind: EnemyKind; hp: number; maxHp: number; shield: number; age: number; fire: number; baseY: number; phase: number; variant: number; warned: boolean };
export type Particle = Point & { vx: number; vy: number; life: number; color: string; size: number };
export type ItemKind = Weapon | 'HEAL' | 'BOMB' | 'BARRIER' | 'DRONE';
export type Item = Rect & { kind: ItemKind };
export type Obstacle = Rect;
export type Ally = Point & { id: AllyId; fire: number; cooldown: number; support: number };
export type Dialogue = { name: string; text: string };
export type Status = 'intro' | 'playing' | 'choice' | 'clear' | 'ending' | 'over';
export type Snapshot = { status: Status; mode: Mode; stage: number; title: string; score: number; time: number; hp: number; maxHp: number; bombs: number; combo: number; maxCombo: number; kills: number; bosses: number; weapon: Weapon; level: number; hyper: number; hyperTime: number; slow: number; dash: number; allies: string; dialogue: Dialogue | null; boss: { name: string; hp: number; phase: number } | null; warning: boolean; tier: string; barrier: number };
export const clamp = (n: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, n));
export const overlaps = (a: Rect, b: Rect) => a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y;
